export const UPDATE_NEW_ARRIVALS = "UPDATE_NEW_ARRIVALS";
export const UPDATE_NEW_ARRIVALS_SUCCESS = "UPDATE_NEW_ARRIVALS_SUCCESS";
export const UPDATE_NEW_ARRIVALS_FAIL = "UPDATE_NEW_ARRIVALS_FAIL";

export const UPDATE_CURRENT_PRODUCT = "UPDATE_CURRENT_PRODUCT";
export const UPDATE_CURRENT_PRODUCT_SUCCESS = "UPDATE_CURRENT_PRODUCT_SUCCESS";
export const UPDATE_CURRENT_PRODUCT_FAIL = "UPDATE_CURRENT_PRODUCT_FAIL";